[package]
name = "creative_zone_builder"
version = "1.0.0"
authors = ["hardliner66 <hardliner66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed="5.1.0"
argparse = "0.2.2"
zip = "0.5.2"
